# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
# first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

LIMIT = 4000000
fib, fib_even = [1, 2], [2]

while fib[-1] + fib[-2] < LIMIT:
    fib.append(fib[-1] + fib[-2])
    if (fib[-1] + fib[-2]) % 2 == 0:
        fib_even.append(fib[-1] + fib[-2])

print (sum(fib_even))